---
- name: Bootstrap a system
  hosts: all
  become: true
  gather_facts: false

  tasks:

    # - name: Bootstrap
      # ansible.builtin.include_role:
        # name: zilux.tools.bootstrap

    - name: Adjust virtual host
      ansible.builtin.include_role:
        name: zilux.tools.install_virthost
