---
- name: Bootstrap a system
  hosts: all
  become: true
  gather_facts: false

  tasks:

    # - name: Bootstrap
      # ansible.builtin.include_role:
        # name: zilux.tools.bootstrap
# 
    # - name: Adjust stuff for hypervisor
      # ansible.builtin.include_role:
        # name: zilux.tools.install_virthost

    - name: Install snap/epel
      ansible.builtin.include_role:
        name: zilux.tools.snap
        
